### ISSUE TITLE
Changes on style and implementing extra div's

### ISSUE THREAD

**Issue by gabrielpoetaa** [VedasreeM/ToDoList#7]
Hi Vedasree M, 
Nice project! I noticed your todoapp could have a bit more margin between the elements and a _delete_ button with fixed size.. I have made some changes, is that ok if I make a pull request to your project?  So you can analyze and see if changes are worth it.

Thank you!

**Comment by VedasreeM** [comment]
Thank you for your feedback and suggestions! I appreciate your willingness to contribute to the project. Please go ahead and submit a pull request with your changes. I'll review them and get back to you.

Thank you!😊
